name: dotnet2
on:
    workflow_dispatch       
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v1
        - name: Build
          run: dotnet build 
        - name: Test
          run: dotnet test --no-build
        - name: Pack nugets
          run: dotnet pack --no-build --output 
        