name: dotnet2
on:
    workflow_dispatch       
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x
        - name: Restore dependencies
          run: dotnet restore   
        - name: Build
          run: dotnet build --no-restore
        - name: Test
          run: dotnet test 
        - name: Pack nugets
          run: dotnet pack --no-build --output 
        